apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay-job-multi-completions
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay
        command: ["cowsay",  "This is a Kubernetes Job!"]
      restartPolicy: Never
  backoffLimit: 4
