apiVersion: v1
kind: Pod
metadata:
  name: mynodeapp-manual
 
spec:
  containers:
  - name: mynodeapp-container
    image: anandr72/mygoapp
    imagePullPolicy: IfNotPresent
    ports: 
      - containerPort: 8080
        protocol: TCP