apiVersion: v1
kind: Pod
metadata:
  name: busy-pod
spec:
  containers:
  - command:
    - sleep
    - "1d"
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busy-cont
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
