apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container
      image: busybox
      command:
      - /bin/sh
      - -c
      - sleep 1d
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/foo
  volumes:
    - name: secret-volume
      secret:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        secretName: db-user-pass
  restartPolicy: Never
